- src/App.js
This adds back the redux provider that was mistakenly removed during the merge conflict resolutions when merging `dev` into `main`
> fix: add back redux provider

- src/components/annual-report/section3/section3Calculations.js
- src/components/annual-report/utils/utils.js
See: https://dhis2.atlassian.net/browse/RWDQA-51
This ticket is to add `chartInfo` for each item in Section 3A to be used for generating the chart.
Example first item from `Maternal Health, National, 2022`
```
{
"section3a": [
{
"name": "ANC 1 coverage - routine and DHS",
"level": 2,
"qualityThreshold": 20,
"surveyValue": 93,
"routineValue": 87.6,
"overallScore": 94.2,
"divergentSubOrgUnits": {
"number": 0,
"percentage": 0,
"names": "",
"noncalculable": ""
},
"chartInfo": {
"name": "ANC 1 coverage - routine and DHS",
"type": "scatter",
"values": [
{
"name": "National",
"survey": 93,
"routine": 87.6,
"divergent": false
},
{
"name": "Region A",
"survey": 90,
"routine": 85.6,
"divergent": false
},
{
"name": "Region B",
"survey": 92,
"routine": 88.4,
"divergent": false
},
{
"name": "Region …
```
> feat: add section 3 chart info [RWDQA-51]

- src/components/annual-report/report-data/section4/section4Calculations.js
See https://dhis2.atlassian.net/browse/RWDQA-52
This PR adds chartInfo in the format discussed on the ticket (see below) 
I've also added a `invalid` property to denote values where the calculations are invalid (these values can be skipped in chart generation).
TBD: the old app does not display a chart if the level of the numerator relation matches the level of the selected Org Unit (boundary org unit). We need to clarify with Olav on what the desired behaviour is here. The old app is skipping the chart here, though theoretically, it could just be generated with the one data point. I think it's probably easier to just generate the chart if we have the one data point. (see https://dhis2.slack.com/archives/C053JT69YD8/p1698330063957719)
**Sample Section4b (Maternal Health > National > …
> feat: add info for Section 4 charts [RWDQA-52]

- src/components/annual-report/Chart.js
- src/components/annual-report/generateChart.js
- src/components/annual-report/section4/SectionFour.js
- src/components/annual-report/section4/section4ChartGenerator.js
This PR (for ticket https://dhis2.atlassian.net/browse/RWDQA-14)
- implements functions for generating charts (scatter with target lines) needed in Section 4
- handle empty `chartInfo.values` case: chart with "No data to display" text is shown
Chart screenshots:
Scatter chart with target lines and outliers using diamond markers:
Same chart with tooltip:
> feat: generate charts for section4 [RWDQA-14]

- i18n/en.pot
- package.json
- src/components/annual-report/generateChart.js
- src/components/annual-report/section3/SectionThree.js
- src/components/annual-report/section3/section3ChartGenerator.js
- yarn.lock
This PR (for ticket https://dhis2.atlassian.net/browse/RWDQA-14)
- adds Highcharts dependency to the app
- implements a component and some functions for generating charts (scatter and bullet) needed in Section 3
- handle invalid `chartInfo.type` case: empty chart with "Chart not available" text is shown
- handle empty `chartInfo.values` case: chart with "No data to display" text is shown
Chart screenshots:
Scatter chart showing plus marker for Routine:
Scatter chart showing triangle markers for divergent values and tooltip:
Bullet chart:
> feat: generate charts for section 3 [RWDQA-14]

- i18n/en.pot
- src/components/annual-report/generateChart.js
- src/components/annual-report/section2/SectionTwo.js
- src/components/annual-report/section2/section2ChartGenerator.js
- src/components/annual-report/section3/section3ChartGenerator.js
- src/components/annual-report/section4/section4ChartGenerator.js
This PR (for ticket https://dhis2.atlassian.net/browse/RWDQA-14)
- implements functions for generating charts (line, column and scatter) needed in Section 2
**NB**: `SectionTwo.js` has inline sample data that needs to be removed once the logic is in place.
For section 2e, only one `<Chart />` component is needed (the second is there only for testing the column chart).
Line chart screenshot:
Scatter chart screenshot:
Column chart screenshot:
> feat: generate charts for section 2 [RWDQA-14]

- src/components/annual-report/section1/SectionOne.js
- src/components/annual-report/section1/section1Calculations.js
This PR adds the chartInfo as discussed on https://dhis2.atlassian.net/browse/RWDQA-56
Note that since there is one chart for the entire section (specifically the chart is for Section 1D), I have just put the `chartInfo` at  the same level as the data for each section. I can move this if desired.
```
{
"section1a": [],
"section1b": [],
"section1c": [],
"section1d": [],
"chartInfo": {},
}
```
> feat: add section1 chartInfo [RWDQA-56]

- i18n/en.pot
- src/components/annual-report/generateChart.js
- src/components/annual-report/section1/SectionOne.js
- src/components/annual-report/section1/section1ChartGenerator.js
This PR (for ticket https://dhis2.atlassian.net/browse/RWDQA-14)
- implements functions for generating chart (multiple lines) needed in Section 1
Chart screenshots:
Multiple line chart with some missing values:
Example of 1 line highlighted by hovering on the correspondent item in the legend:
> feat: generate chart for section 1 [RWDQA-14]

- src/components/config-tabs/ConfigTabs.js
- src/components/config-tabs/ConfigTabs.module.css
- src/components/config-tabs/numerator-relations/EditNumeratorRelationModal.js
- src/components/config-tabs/numerator-relations/NumeratorRelationTableItem.js
- src/components/config-tabs/numerator-relations/NumeratorRelations.js
- src/components/config-tabs/numerator-relations/index.js
- src/components/config-tabs/tab-contents/NumeratorRelations.js
- src/utils/numeratorsMetadataData.js
Still in progress -- did some clean up and started the refactor. Now the entire page doesn't rerender on input change, but the modal still does
Next steps:
Done
- Reorganize some; give Numerator Relations its own dir
- Abstract "edit modal" to its own file to save page rerenders due to form state
- Abstract out `NumeratorRelationsTableItem` to customize modal to each num. rel. item
- Clean up and apply best practices to code
> fix: optimize numerator relations [RWDQA-18]

- src/components/annual-report/section1/SectionOne.js
- src/components/annual-report/section1/section1Calculations.js
- src/components/annual-report/section2/section2abcCalculations.js
- src/components/annual-report/section2/section2dCalculations.js
See https://dhis2.atlassian.net/browse/RWDQA-59. Handles issues caused by data and reportParameters momentarily diverging when report is regenerated with new parameters. Note that the logic for data refetching will also be updated (https://dhis2.atlassian.net/browse/RWDQA-60) so that this should not be an issue, but the work here would prevent 
This PR:
- Section 1: adds in optional chaining to calculations/report. Missing values are prevented from causing errors.
- Section 2: skips over calculations when dx is missing from metadata
- Sections 3/4: does not make any changes. These sections do not need updates as they loop through `configurations` metadata and then will result in NaN values if the underlying values are missing from responses. Since these are consistent across groups, this …
> fix: handle missing info [RWDQA-59]

- src/components/annual-report/section1/section1Calculations.js
See https://dhis2.atlassian.net/browse/RWDQA-44
This PR:
- adds calculations for Increasing/Decreasing trend types in section 1d (note that forecast values are floored at zero in old app https://github.com/dhis2/who-data-quality-app/blob/c3fac5237e540e3eac5640c3995ec14687e23ea8/src/appCore/dqAnalysisConsistency.js#L474 and this is replicated here)
- adds the `th` comparison (that is the comparison where we do not compare against the overall OU comparison)
- does some minor clean up (e.g. use `getMean` from mathService for calculating average, changes some variable names to make them a bit clearer when the constant/non-constant calculation distinction was added)
> fix: forecast values/non-ou comparison [RWDQA-44]

- src/components/annual-report/ReportData.js
- src/components/annual-report/section1/section1Calculations.js
- src/components/annual-report/section1/useSectionOneData.js
- src/components/annual-report/section2/SectionTwo.js
- src/components/annual-report/section2/useSectionTwoData.js
- src/components/annual-report/utils/utils.js
- src/components/report-parameter-selector/getReportParameters.js
- src/utils/utils.js
This PR adds handling for data element operands (see https://dhis2.atlassian.net/browse/RWDQA-78)
Here I'm assuming that all numerators will have a data element operand id (this seems to be required by the old app's UI). If that's not the case, the calculations could be modified slightly.
The configurations at https://demos.dhis2.org/dq/api/dataStore/dataQualityTool/settings have some dataElementOperandIDs where there is only an ID (i.e. not an `{deUID}.{cocUID}`), so I've also added handling in for retrieving the default COC and using that as the COC if the COC is missing from the data element operand id. I don't actually know why this occurs because the old app seems to sometimes saves a data element operand that is `{deUID}.{defaultCOCUID` and other times just saves `{deUID}`. This …
> fix: data element operands [RWDQA-78]

- src/components/annual-report/common/InterpretationsField.js
- src/components/annual-report/common/InterpretationsField.module.css
- src/components/annual-report/common/index.js
- src/components/annual-report/section1/SectionOne.js
- src/components/annual-report/section1/SectionOne.module.css
- src/components/annual-report/section2/SectionTwo.js
- src/components/annual-report/section3/SectionThree.js
- src/components/annual-report/section4/SectionFour.js
https://dhis2.atlassian.net/browse/RWDQA-15
Made a simple component to drop in anywhere in the report, and added some basic styles to make it look good in print. I also thought it made sense to hide empty fields during printing.
Web page:
Print preview:
Here are some things I noticed we'll need to do when we do the rest of the print styles:
1. Hide the header bar and selector bar and other non-report UI
2. Be able to print the whole report -- for some reason, it can only print the visible page right now
3. Enable page breaks so tables aren't cut in half
4. Graphs need to be smaller
> feat: add interpretations fields to report [RWDQA-15]

- i18n/en.pot
- src/components/config-tabs/numerators/DataElementDataSetSelect.js
- src/components/config-tabs/numerators/DataElementSelect.js
- src/components/config-tabs/numerators/DataElementTypeRadios.js
- src/components/config-tabs/numerators/DataElementVariableSelect.js
- src/components/config-tabs/numerators/DataMappingForm.js
- src/components/config-tabs/numerators/EditNumeratorModal.js
- src/components/config-tabs/numerators/NumeratorTableItem.js
- src/components/config-tabs/numerators/useIsFieldRequired.js
Issue: https://dhis2.atlassian.net/browse/RWDQA-79
Adjusts the form state a bit to be able to check if there's a previous mapping ID, then makes the data mapping fields required for a new numerator OR an existing numerator with a _new_ data item selected
> feat: validate data mapping fields [RWDQA-79]

- src/components/annual-report/section1/section1Calculations.js
This PR:
- alphabetizes items in Sections 1a,1b,1d (including subunit names)  [https://dhis2.atlassian.net/browse/RWDQA-77]
- adds rounding that was missing on the divergent subunits percentages in these sections
> fix: alphabetical order, rounding [RWDQA-77]

- src/components/report-parameter-selector/OrgUnitSelector.js
See: https://dhis2.atlassian.net/browse/RWDQA-91
This fixes an issue that was introduced when we updated the logic on the Org Unit Level selection.
This update will make the OrgUnitLevel clear out properly when a new Org Unit is selected.
> fix: clear invalid org unit level [RWDQA-91]

- src/components/annual-report/section2/SectionTwo.js
- src/components/annual-report/section2/section2eCalculations.js
See https://dhis2.atlassian.net/browse/RWDQA-93
Fixes some issues from Section 2E:
- Tables say “Denominators” when they should say “Indicators
- Divergent region names aren’t shown in the table
- “Equal across org units” graph line doesn’t look right (slope is incorrect)
- “Equal across org units” divergent calculations are incorrect
These are now fixed, example:
> fix: section 2E issues [RWDQA-93]

- src/components/annual-report/ReportData.js
- src/components/annual-report/ReportData.module.css
- src/components/annual-report/section2/SectionTwo.js
- src/components/annual-report/section2/SectionTwo.module.css
https://dhis2.atlassian.net/browse/RWDQA-97
Adds some margins to make them look better -- "no data" is simulated in these demos:
> fix: margins around "no data" info boxes [RWDQA-97]

- src/components/annual-report/section1/section1Calculations.js
- src/components/annual-report/section1/useSectionOneData.js
See https://dhis2.atlassian.net/browse/RWDQA-92
This PR fixes cases where requests were failing because an underlying category combo was designated skipTotals: true (I'm not sure why these requests would fail given that we were not requesting the total counts, but rather the counts disaggregated by category option combo 🤷‍♂️, but we can do these requesst differently and avoid the issue).
This fix uses data element operand directly as a dx request. Since we are now requiring all numerators to have a data element operand (and filtering them out if they don't), this should not pose an issue (and is simpler than what I previously implemented, which did the request with `co` as a parameter, which then necessitated some additional work for handling defaults)
(Tested with …
> fix: issues with skipTotal categoryCombo [RWDQA-92]

- src/components/config-tabs/denominators/DenominatorTableItem.js
This PR, implements the same validation done on numerators before deletion. 
In case the denominator to be deleted is associated with another object the user should be warned before they delete it. 
Jira Ticket: https://dhis2.atlassian.net/jira/software/c/projects/RWDQA/boards/137?assignee=5c51f72f3e729341b3517497&selectedIssue=RWDQA-101
> fix: validate denominator's relations with other objects before delete [RWDQA-101]
